fixed gcc 11.x warning

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -131,7 +131,12 @@ echo "# " > Makefile
 echo "# Copyright (C) Niklaus F.Schen." >> Makefile
 echo "# " >> Makefile
 echo -e "CC\t\t= $cc" >> Makefile
-echo -e "FLAGS\t\t= -Iinclude -Imelang -c -Wall -ggdb -Werror -O3 -fPIC" >> Makefile
+gccver=`gcc -dumpversion`
+if [ "$?" == "0" -a $gccver -ge 11 ]; then
+    echo -e "FLAGS\t\t= -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC" >> Makefile
+else
+    echo -e "FLAGS\t\t= -Iinclude -Imelang -c -Wall -ggdb -Werror -O3 -fPIC" >> Makefile
+fi
 if ! case $sysname in MINGW*) false;; esac; then
     echo -e "MELONSO\t\t= libmelon.dll" >> Makefile
     echo -e "MELONA\t\t= libmelon.lib" >> Makefile
